version: '3'
services:
  trip-calculator-ui:
    build:
      context: .
      image: michaeltarleton/trip-calculator-ui
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
